### ISSUE TITLE
Resources not listed after download

### ISSUE THREAD

**Issue by emlaabs** [sonar-intellij-plugin/sonar-intellij-plugin#175] opened 2017-03-01 18:05 UTC
I am trying to associate my project to its resources on a remote sonar server.  After downloading, I am unable to find my resource listed.  Our sonarqube server has over 1400 projects currently listed.  I am wondering if there is a limit to the number of resources that the plugin downloads and if that could be causing my project to not be listed.  Any advice on how to research this and diagnose my issue would be greatly appreciated.

**Comment by omayevskiy** [comment] 2017-09-20 10:27
closing: duplicate of #179

**Closed by omayevskiy** 2017-09-20 10:27 UTC

**Comment by Manish2005** [comment] 2018-10-31 08:52
This is not a duplicate of #179 . #179 is about getting error response while trying to download the resources. I think this is about not fetching ALL the available resources.
I am facing a similar problem. My Sonar server has 360 projects but Download Resources only shows about 120 of those. And I'm not sure why.

**Comment by zietas** [comment] 2018-12-17 08:45
I have the same issue in my current setup. My Sonar server holds above 500 projects and it seems that "Download resource" action does not download everything. It's a valid issue.
