### ISSUE TITLE
Local analysis keeps listing new issue even after it was fixed (stale cache?)

### ISSUE THREAD

**Issue by christianbalzer** [sonar-intellij-plugin/sonar-intellij-plugin#133] opened 2015-10-08 11:44 UTC
A local analysis found several issues; one of which won't disappear after all issues were fixed and the analysis was re-run. Is the cache stale? Can it be reset?

The rule affected is squid:UnusedPrivateMethod, in case that helps...
(The method was removed, so there is no trace of it in the class under local analysis...)

**Comment by omayevskiy** [comment] 2015-10-08 13:15
is duplicate of issue: #114
I workaround it by pushing my changed and analysis by sonar, after it disappears.

**Closed by omayevskiy** 2015-10-08 13:15 UTC
