### ISSUE TITLE
SonarQube 5.0 - new issue not shown

### ISSUE THREAD

**Issue by apolit** [sonar-intellij-plugin/sonar-intellij-plugin#104] opened 2015-01-16 08:41 UTC
```
INFO 09:19:21.874 > finished with exit code 0 in 02:33:374
INFO 09:19:21.874 > Reading issues from [HERE GOES PROPER PATH]]/target/sonar/sonar-report.json
INFO 09:19:22.006 > Found 211 issues in the SonarQube report
INFO 09:19:22.007 > Creating index from SonarQube report
INFO 09:19:22.017 > Start processing 1 files and 211 issues with 4 threads
INFO 09:19:22.026 > Finished creating index from SonarQube report with 0 issues in 00:00:018
```
But there is a new issue in the sonar-report.json and it is not parsed and shown in Idea.
Old issues are shown correctly.

**Comment by omayevskiy** [comment] 2015-01-16 09:55
did not look at sonar 5 yet, could be they changed the format

**Comment by omayevskiy** [comment] 2015-01-17 19:41
hello again,
today executed analysis of the plugin src code itself using sonarqube 5.0, Intellij CE 14.0.2 and Intellij Ultimate 13.1.6. Works for me so far.


INFO 09:19:22.017 > Start processing 1 files and 211 issues with 4 threads
INFO 09:19:22.026 > Finished creating index from SonarQube report with 0 issues in 00:00:018

...1 files... it looks like your analysis scope is only 1 file, if there are no issues in that file, the plugin will not popup any issues also if they are in the report.

**Comment by apolit** [comment] 2015-01-19 09:15
Hello,
Yes, my scope is one file, but for whole module it also didn't work. There is a new issuse, I have checked sonar-report.json using text editor. The project is multi module - it could be the case. A path is like this:
root/module-A/module-AA
I use community edition.

**Comment by omayevskiy** [comment] 2015-01-19 09:28
> The project is multi module - it could be the case.
Did you read the section about multi module projects?

> I use community edition.
Not a problem, the plugin is free and not from jetbrans ;-)

**Comment by apolit** [comment] 2015-01-19 09:59
The module assignment has been configured before all the tests.

Here is the issue from sonar-report.json. File names was replaced. Maybe isNew property was named differently in Sonar 4.x ?
```
{"key":"e776a2ce-c91e-44c7-9960-58cf970fb726","component":"groupId:artifactId:src/main/java/package/Class.java","line":52,"message":"Avoid unused local variables such as 'test'.","severity":"MAJOR","rule":"pmd:UnusedLocalVariable","status":"OPEN","isNew":true,"creationDate":"2015-01-19T10:37:58+0100","updateDate":"2015-01-19T10:37:58+0100"}
```

**Comment by omayevskiy** [comment] 2015-01-19 10:14
> groupId:artifactId:src/main/java/package/Class.java

check if "groupId:artifactId" is correct
check if "src/main/java/package/Class.java" is under analysis scope
check working directory "working dir: /path/to/your/app"

**Comment by apolit** [comment] 2015-01-20 08:27
I have analyzed sonar-report.json, there is a difference:
In this plugin sources component is like this:
```
"component": "de.mobile.dealer:dealer-admin:de.mobile.dealer.assembler.MakeModelOptionsAssembler",
```
In my sonar-report.json component is like this:
```
"component": "de.mobile.dealer:dealer-admin:src/main/java/de/mobile/dealer/assembler/MakeModelOptionsAssembler.java",
```

**Comment by omayevskiy** [comment] 2015-01-20 09:57
this is fine, sonar saves components in different formats depends on the analyzer.

form sonar-report.json if you analyse the source code of the plugin itself:
```
{
  "key": "339ac23a-5a08-44a0-8859-b139fd87021d",
  "component": "org.intellij.sonar:sonar-intellij-plugin:src\/main\/java\/org\/intellij\/sonar\/DocumentChangeListener.java",
  "line": 148,
  "message": "At most one statement is allowed per line, but     2 statements were found on this line.",
  "severity": "MAJOR",
  "rule": "squid:S00122",
  "status": "OPEN",
  "isNew": true,
  "creationDate": "2015-01-17T20:35:27+0100",
  "updateDate": "2015-01-17T20:35:27+0100"
}
```

**Comment by omayevskiy** [comment] 2015-01-20 22:55
just came around with similar issue to yours:

double check the:

INFO 09:19:21.874 > Reading issues from [HERE GOES PROPER PATH]]/target/sonar/sonar-report.json

[HERE GOES PROPER PATH]]

if you have hard coded path for one project, but then analyse another project, then the hard coded one is wrong for other project. If this is your case use $WORKING_DIR/target/sonar/sonar-report.json instead.

**Comment by apolit** [comment] 2015-01-21 08:11
Path is ok. I will try to setup plugin development and debug later

**Comment by apolit** [comment] 2015-01-21 12:21
Here is the bug: 
SonarCompoenntToFIleMatcher.java
```
        // component = "sonar:project:src/main/java/org/sonar/batch/DefaultSensorContext.java";
        // resourceKey = "sonar:project"
        if (!isEmptyOrSpaces(resourceKeyFromConfiguration) && !componentFromSonar.startsWith(resourceKeyFromConfiguration)) {
            return false;
        }
```
resourceKey = "sonar:project:branch" when I debug the plugin
Fix
```
resourceKeyFromConfiguration = resourceKeyFromConfiguration.substring(0, resourceKeyFromConfiguration.lastIndexOf(':'));
```
works for me, I got new issue in inspection window :-) But I think you know better place to put this fix.

**Comment by omayevskiy** [comment] 2015-01-21 12:38
:+1: 
would you be so nice and create a pull request?

**Comment by omayevskiy** [comment] 2015-01-21 14:18
ok so it was a sonar branch issue, it looks like make sense to add a "sonar branching support" checkbox somewhere in the project/module settings

**Comment by omayevskiy** [comment] 2015-01-21 19:56
duplicate of #19

**Closed by omayevskiy** 2015-01-21 19:56 UTC

**Comment by apolit** [comment] 2015-01-22 08:32
Moreover, when assiging module to a sonar resource when there are multiple mulit-module projects with multiple branches, the selection list is huge. Need some filtering there.

**Comment by omayevskiy** [comment] 2015-01-22 10:27
the filtering was already described in #96

**Comment by apolit** [comment] 2015-01-22 10:51
Could you include my fix (with condition if resource has the segment with branch) until the branches handling will be fully implemented?

**Comment by omayevskiy** [comment] 2015-01-22 11:12
"with condition if resource has the segment with branch"
how would you check it? :-)
What I wanted to do is implement configurable checkbox to enable/disable the "fix", see comment in the pull request.

**Comment by apolit** [comment] 2015-01-22 11:20
At a first glance the condition should check if there are two ';' in resource key.
At a second glance you may take into account a  sonar-report.json SonarQube version property.
But A checkbox may be a better idea, you know your plugin better :-)

**Comment by omayevskiy** [comment] 2015-01-22 11:20
it looks like the key is always like:

"sonar:project"

and with branch:

"sonar:project:branch"

but really from everything seeing from sonar I would not give a warranty ;-)

**Comment by omayevskiy** [comment] 2015-01-22 11:23
> At a second glance you may take into account a sonar-report.json SonarQube version property.
branching support was introduces already earlier if I am not wrong

**Comment by apolit** [comment] 2015-01-22 11:30
> branching support was introduces already earlier if I am not wrong 
Yes, but earlier there was no branch segment in resourceKey and plugin was working properly.
It works for us with SonarQube 4.4 with branches, with same modules configuration as now.

**Comment by omayevskiy** [comment] 2015-01-22 11:33
great!
I am afraid I will need to look into branching support in more detail on next free time period ;-)
