### ISSUE TITLE
Errors in las webstorm version 2016.3

### ISSUE THREAD

**Issue by davidlampon** [sonar-intellij-plugin/sonar-intellij-plugin#164] opened 2016-11-18 15:43 UTC
Just found this issue on the last version of webstorm:

![screen shot 2016-11-18 at 16 41 41](https://cloud.githubusercontent.com/assets/6107319/20435880/13d76570-adae-11e6-8851-20e02dc298c8.png)
![screen shot 2016-11-18 at 16 41 47](https://cloud.githubusercontent.com/assets/6107319/20435881/13dd8dc4-adae-11e6-9424-c96731a05e31.png)

**Comment by mwalter-healthagen** [comment] 2016-11-22 15:14
Hi Sonar Intellij Plugin,

I am getting the same error, I am trying to run this plugin on WebStorm 2016.3
Build #WS-163.7743.25, built on November 10, 2016
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

And I am getting the following error.
Could you help me please?

Thanks!
-matt

com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:324)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:392)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:280)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:280)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:237)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by ratmir-by** [comment] 2016-11-25 14:39
The same for me(

`com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile; 
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile; 
at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)`

**Comment by guymahieu** [comment] 2016-11-29 15:18
Same here on Intellij IDEA 2016.3.

**Comment by stingus** [comment] 2016-11-29 21:19
+1

**Comment by josezuazo** [comment] 2016-11-30 15:55
Same error on PyCharm 2016.3

**Comment by omayevskiy** [comment] 2016-12-09 13:22
duplicate of #168

**Closed by omayevskiy** 2016-12-09 13:22 UTC

**Comment by mcmahonjohn** [comment] 2017-03-28 16:22
@omayevskiy Technically, #168 was the duplicate of this issue.
